INSERT INTO TB_CLIENT (ID, NAME, BALANCE) VALUES (10, 'Client 1', 100);
INSERT INTO TB_CLIENT (ID, NAME, BALANCE) VALUES (11, 'Client 2', 200);
INSERT INTO TB_CLIENT (ID, NAME, BALANCE) VALUES (12, 'Client 3', 300);